<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Authentication Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used during authentication for various
    | messages that we need to display to the user. You are free to modify
    | these language lines according to your application's requirements.
    |
    */

    /* Login page */
    'loginTitle' => 'Sign in to PMBot',
    'loginSubTitle' => 'Enter your details below',
    'loginUserNameLabel' => 'User Name',
    'loginUserNamePlaceHolder' => 'Enter user name',
    'loginEmailLabel' => 'Email address',
    'loginEmailPlaceHolder' => 'Enter UserName / E-Mail Address',
    'loginPasswordLabel' => 'Password (PMBot Application)',
    'loginPasswordPlaceHolder' => "Enter (PMBot application) password",
    'loginLdapPasswordLabel' => 'Password',
    'loginLdapPasswordPlaceHolder' => "Enter password",
    'forgotPassword' => 'forgot password ?',
    'remember' => 'Keep me logged in',
    'loginButton' => 'sign in',
    'userLoginPostURl' => 'user-login',
    'userMFAPostURl' => 'user-mfa',

    'mfaTitle' => 'Enter Code',
    'mfaOTPLabel' => 'Enter the verification code generated by Google/Microsoft Authenticator app on your phone:',
    'mfaOTPPlaceHolder' => "Enter code",
    'mfaSubmitButton' => 'submit',

    /* Forgot password page */
    'forgotPasswordTitle' => 'Need help with your password?',
    'forgotPasswordSubTitle' => 'Enter the email you use for PMBot, and we’ll help you create a new password.',
    'forgotPasswordEmailLabel' => 'Email address',
    'forgotPasswordEmailPlaceHolder' => 'Enter email',
    'forgotPasswordButton' => 'Send Password Reset Link',

    /* Reset password page */
    'resetPasswordTitle' => 'Reset Password',
    'resetPasswordEmailLabel' => 'Email address',
    'resetPasswordEmailPlaceHolder' => 'Enter email',
    'resetOldPasswordLabel' => 'Old Password',
    'resetOldPasswordPlaceHolder' => "Enter password",
    'resetNewPasswordLabel' => 'New Password',
    'resetNewPasswordPlaceHolder' => "Enter password",
    'resetConfirmPasswordLabel' => 'Confirm Password',
    'resetConfirmPasswordPlaceHolder' => "Re-Enter password",
    'resetButton' => 'Reset',

    /* Logout */
    'loginOutButton' => 'sign out',

    'failed' => 'These credentials do not match our records.',
    'throttle' => 'Too many login attempts. Please try again in :seconds seconds.',

];
